version: '3.0'

services:
  fe:
    build: "./fe"
    restart: always
    ports:
      - 3000:3000
    networks:
      - frontend
    env_file:
      - ./fe/.env
  api:
    build: "./api"
    restart: always
    env_file:
      - ./api/.env
    ports:
      - 5003:5000
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend: